### ISSUE TITLE
Less peerDependencies

### ISSUE THREAD

**Issue by ratson** [umidbekkarimov/react-async-state#17]
Except `react`, is it necessary to require others to be `peerDependencies`?

**Comment by umidbekkarimov** [comment]
I didn't want to add any dependencies, so users can chose explicit versions of dependencies they want to use, so if there would be any problem with some of these packages I wouldn't have to publish new version to fix it. Also there wouldn't be multiple usages of same module with different versions.

I do not have a big experience with npm modules, so I open for suggestions if there any.

**Comment by ratson** [comment]
FWIK, this means the user can not have different versions of the same library being used, which could cause problem if someone have been using an older version.

Allow usage of same modules with difference version is actually a feature of `node` module system, `npm@3` will do `dedupe` during install if possible.

You can set the dependencies version to `*` or version range, e.g. `3.x.x`, then you don't need to publish new version when dependencies updated.

**Comment by umidbekkarimov** [comment]
👍 Thank you for suggestions! [v0.3.0](https://www.npmjs.com/package/react-async-state) published.
